### ISSUE TITLE
HTML Framework

### ISSUE THREAD

**Issue by mjzabriskie** [mjzabriskie/marvel-ous-gifs#1]
Get the basic HTML structure in place

**Comment by luimr88** [comment]
![FF5E95F5-C4CD-46B7-B056-99746A0C2E5D](https://user-images.githubusercontent.com/78315917/164362744-2f072441-3a98-4a84-9555-e14da445a905.jpeg)
![16951185-E4C3-4547-B703-BB908E931ABB](https://user-images.githubusercontent.com/78315917/164362747-898c3baa-fd43-46a2-8dac-ae05b1c104b7.jpeg)
